### ISSUE TITLE
Sobre tu presentación...

### ISSUE THREAD

**Issue by elin-winter** [pdepjm/2024-tp0-presentacion-AscarlatoUTN#3]
Hola Ale! 

Solo quería decirte que me encantó tu foto con el perrito, muy copada aunque hubiera preferido un gato jajaja. Me encantaría saber más de vos, si fuera vos agregaría una sección con hobbies, películas favoritas u helado preferido, lo que quieras!

Más allá, muy buena presentación :)

**Comment by AscarlatoUTN** [comment]
Gracias, lo tendré en cuenta para versiones próximas.
